# Generated by Django 5.1.1 on 2024-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('product_image_url', models.URLField(max_length=1024)),
                ('product_link', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_product_id', models.CharField(max_length=255)),
            ],
        ),
    ]
