# Generated by Django 5.1.1 on 2024-09-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
